[tool]
[tool.poetry]
name = "OldUserBot_Deployer"
version = "1.0"
description = "Automatic Deploy AsenaUserBot to Heroku"
authors = ["Vusal <Vusal@vu7o1>"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
